# Generated by Django 6.0 on 2026-01-06 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('expected_output', models.ImageField(blank=True, null=True, upload_to='media/prompts/expected_output/')),
            ],
        ),
    ]
